In [8]:
import numpy as np
import pandas as pd
import os

In [10]:
from sklearn.datasets import load_boston
df=load_boston()

In [11]:
type(df)

sklearn.utils.Bunch

In [12]:
df.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [17]:
print(df.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [ ]:
print(df.DESCR)

In [ ]:
boston=pd.DataFrame(df.data,columns=df.feature_names)
boston.head()

In [ ]:
boston.isnull()

In [ ]:
boston.isnull().sum()

In [27]:
from sklearn.model_selection import train_test_split

X=boston.drop('MEDV',axis=1)
Y=boston['MEDV']

X_train,X_test,Y_test=train_test_split(X,Y,test_size=0.15)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

KeyError: ignored